spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/myrealm"
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
