spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/myrealm"
  config:
    import: optional:configserver:http://api-config-server:8888
  application:
    name: api-gateway
