package co.edu.unicauca.vistas.principal;

import co.edu.unicauca.infraestructura.Observer;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.Timer;

/**
 *
 * @author HSVSTT2
 */
public class VtnNotify extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form VtnPrincipalAdmin
     */
    public VtnNotify() {

        setLocation(450, 150);
        try {
            FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNotify = new javax.swing.JLabel();
        lblTituloNotify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNotify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotify.setForeground(new java.awt.Color(255, 255, 255));
        lblNotify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotify.setText("Creado con exito.");

        lblTituloNotify.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNotify.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloNotify.setText("Notificacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloNotify)
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override

    public void update(Object o) {
        lblNotify.setText("Creado con éxito");

        // Obtener las dimensiones de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtener el tamaño de la ventana
        int windowWidth = this.getWidth();
        int windowHeight = this.getHeight();

        // Calcular la posición para colocar la ventana en la parte baja de la pantalla
        int x = (screenSize.width - windowWidth)-50; // Centrar horizontalmente
        int y = screenSize.height - windowHeight - 50; // Ajustar 50px desde el borde inferior

        // Establecer la posición de la ventana
        this.setLocation(x, y);

        // Hacer la ventana visible
        this.setVisible(true);

        // Temporizador para cerrar después de 3 segundos
        javax.swing.Timer timer = new javax.swing.Timer(3000, e -> this.dispose());
        timer.setRepeats(false);
        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNotify;
    private javax.swing.JLabel lblTituloNotify;
    // End of variables declaration//GEN-END:variables
}
